baseURL: https://yukidev.net
languageCode: en-us
title: yukidev
theme: PaperMod
pluralizeListTitles: false

params:
  assets:
    favicon: "assets/favicon.ico"
    favicon16x16: "assets/favicon-16x16.png" 
    favicon32x32: "assets/favicon-32x32.png" 
    apple_touch_icon: "assets/apple-touch-icon.png"
  profileMode:
    enabled: true
    Title: Welcome to my blog.
    subtitle: >
      PGP Public [Key](content/yuki.asc) (Fingerprint: E97D 6124 2700 292C 4F45 E4D0 B793 8CF5 1D1A 72C8)
    buttons:
     - name: Posts
       url: "years/"
     - name: About
       url: "about/"
  socialIcons:
    - name: x
      url: https://x.com/nomad0481
    - name: github
      url: https://github.com/yukidevv
    - name: email
      url: mailto:nomad048@gmail.com
    - name: rss
      url: https://yukidev.net/index.xml
  customCSS: ["/css/custom.css"]
menu:
  main:
    - identifier: search
      name: Search
      url: "search/"
      weight: 10
taxonomies:
  category: "years"