baseURL: https://yukidevv.github.io
languageCode: en-us
title: Blog
theme: PaperMod
pluralizeListTitles: false

params:
  profileMode:
    enabled: false
    title: BlogBlog

  homeInfoParams:
    Title: yukidevv 
  socialIcons:
    - name: twitter
      url: https://twitter.com/nomad0481
    - name: github
      url: https://github.com/yukidevv

menu:
  main:
    - identifier: about  
      name: About
      url: about/about
      weight: 10
    - identifier: blog
      name: Blog
      url: post/
      weight: 10
